### ISSUE TITLE
My Class

### ISSUE THREAD

**Issue by Varun-garg** [Varun-garg/GBU_Timetables#1]
This project is for those students interested in GBU Winter of Code.

Please review our [contribution Guidelines](https://github.com/Varun-garg/GBU_Timetables/blob/master/CONTRIBUTING.md).

### Project
> Other than favorites there should be a preference `My Class`, which is like favorites but for one timetable / section only. This will help in various ways such as attendance management and different notifications. 

### Mentors
1. Dr. Amit K Awasthi @awasthi 
2. Varun Garg @varun-garg

Both mentors can help you with development, but in case you are working closely to database @awasthi  will be more helpful.

### Labels.
For each project you will see a label, they are explained as:
1. Easy: For those new to programming.
2. Medium: For those who are comfortable in programming but not Android.
3. Hard: Only for those who are comfortable with android and have some experience.

### Proposal
If you are interested in this project, please submit a proposal for it. In our case it is done by explaining the design of code you will be writing.

**Comment by ritikchanna** [comment]
Can be done by adding an expanding fab in mainactivity to support of adding myclass which can stored and retrieved using prefs.

**Comment by Varun-garg** [comment]
Merged, Nice job @ritikchanna
