### ISSUE TITLE
Fix UpdateDatabaseService.java

### ISSUE THREAD

**Issue by Varun-garg** [Varun-garg/GBU_Timetables#6]
This project is for those students interested in GBU Winter of Code.

Please review our [contribution Guidelines](https://github.com/Varun-garg/GBU_Timetables/blob/master/CONTRIBUTING.md).

### Project
> `UpdateDatabaseService.java` is a background service to check and update timetable database once in a day and drop a notification. It is based on `UpdateDatabaseOnlineTask.java` (used when application is started, this works). For some reason our background service ( `UpdateDatabaseService.java`) is not working and could use some help.

### Mentors
1. Dr. Amit K Awasthi @awasthi 
2. Varun Garg @varun-garg

Both mentors can help you with development, but in case you are working closely to database @awasthi  will be more helpful.

### Labels.
For each project you will see a label, they are explained as:
1. Easy: For those new to programming.
2. Medium: For those who are comfortable in programming but not yet Android.
3. Hard: Only for those who are comfortable with android and have some experience.

### Proposal
If you are interested in this project, please submit a proposal for it. In our case it is done by explaining the design of code you will be writing.

**Comment by k1941996** [comment]
the problem is that there is no usage of the function startservice() and stopservice()
````
//Method to start the service
 public void startService() 
	{
        startService(new Intent(getBaseContext(), UpdateDatabaseService.class));    
}
 // Method to stop the service
    public void stopService(View view) 
	{
        stopService(new Intent(getBaseContext(), UpdateDatabaseService.class));
    }
````
so to start it we need to declare the startService() method in the onCreate method of the mainActivity
or we may start this in onDestroy() method

**Comment by Varun-garg** [comment]
Hey @k1941996, thanks for taking interest in this project. It's good to see that you came up with a potential solution so early, however to check if the service is working perfectly it should be able to regularly drop a notification for:

1. Database updated (for which code is likely to already present in the service)
2. Database already up to date (only for our debugging, we will disable this before merging / releasing it) 

The database operation works using `UpdateDatabaseOnlineTask.java` , the task works fine from `MainActivity`, however it may also be incorrectly called / used from our service.`

**Comment by Varun-garg** [comment]
Hey @k1941996 , I am sorry to inform you that this project was taken by @ritikchanna . His was ready with a solution and the solution was a bit better than what you proposed. He used a `BootReciever` to start service on boot as well as an alarm manager to check for updates daily. Please go for another project.

In future if anyone submits a pull request for a project without a proposal, and when someone else has already submitted the proposal we won't merge it right away To avoid this problem he is requested to submit a proposal and the best one will be selected for the job.
